export const NPM_FRAMEWORK_MAP: Record<string, string> = {
  react: 'React',
  'react-dom': 'React',
  next: 'Next.js',
  vue: 'Vue.js',
  nuxt: 'Nuxt.js',
  '@angular/core': 'Angular',
  svelte: 'Svelte',
  express: 'Express',
  fastify: 'Fastify',
  nestjs: 'NestJS',
  '@nestjs/core': 'NestJS',
  tailwindcss: 'Tailwind CSS',
  prisma: 'Prisma',
  '@prisma/client': 'Prisma',
  mongoose: 'MongoDB/Mongoose',
  sequelize: 'Sequelize',
  typeorm: 'TypeORM',
  'socket.io': 'Socket.io',
  graphql: 'GraphQL',
  'apollo-server': 'Apollo GraphQL',
  redux: 'Redux',
  zustand: 'Zustand',
  vite: 'Vite',
  webpack: 'Webpack',
  electron: 'Electron',
  'react-native': 'React Native',
  expo: 'Expo',
  jest: 'Jest',
  mocha: 'Mocha',
  cypress: 'Cypress',
  'docker-compose': 'Docker'
}

export const PYTHON_FRAMEWORK_MAP: Record<string, string> = {
  django: 'Django',
  flask: 'Flask',
  fastapi: 'FastAPI',
  tensorflow: 'TensorFlow',
  torch: 'PyTorch',
  pytorch: 'PyTorch',
  numpy: 'NumPy',
  pandas: 'Pandas',
  'scikit-learn': 'scikit-learn',
  sklearn: 'scikit-learn',
  keras: 'Keras',
  celery: 'Celery',
  sqlalchemy: 'SQLAlchemy',
  pytest: 'pytest'
}
